### Fetches all todos
curl https://localhost:7235/todos

### Fetches completed todos
curl https://localhost:7235/todos/completed

### Fetches incomplete todos
curl https://localhost:7235/todos/incomplete

### Get todo by id
curl https://localhost:7235/todos/33333333-3333-3333-3333-333333333333

### Create Todo

@newTodoName = "walk dog"
@newTodoIsComplete = true

# @name createTodo

curl -X POST -H "Content-Type: application/json" -d '{"name":{{newTodoName}},"isComplete":{{newTodoIsComplete}}}' https://localhost:7235/todos

### Update Todo

@todoId = {{createTodo.response.body.id}}

# @name replaceTodo
curl -X PUT -H "Content-Type: application/json" -d '{"name":{{newTodoName}}, "isComplete":false}' https://localhost:7235/todos/{{todoId}}

### Delete Todo

@todoId = {{createTodo.response.body.id}}

# @name replaceTodo
curl -X DELETE https://localhost:7235/todos/{{todoId}}